name: Get latest OSM PBF from Geofabrik

on:
  schedule:
    - cron: '30 7 * * *'
  push:
    tags:
      - test.fetch*

jobs:
  fetch-pbf:
    runs-on: ubuntu-latest
    env:
      DAILY_PBF: taiwan-daily.osm.pbf
      DAILY_PBF_MD5: taiwan-daily.osm.pbf.md5
      github_api_token: ${{ secrets.GITHUB_TOKEN  }}
      owner: typebrook
      repo: mapstew
      tag: daily-taiwan-pbf

    steps:
      - name: Download latest osm.pbf from geofabrik
        uses: wei/curl@v1
        with:
          args: -O http://download.geofabrik.de/asia/taiwan-latest.osm.pbf
      - run: mv taiwan-latest.osm.pbf $DAILY_PBF
      - name: Upload PBF file to Release Asset
        uses: typebrook/github-release@v2
        env:
          type: asset
          filename: ${{ env.DAILY_PBF }}
          overwrite: true

      - run: echo $(md5sum $DAILY_PBF) > $DAILY_PBF_MD5
      - name: Upload MD5 to Release Asset
        uses: typebrook/github-release@v2
        env:
          type: asset
          filename: ${{ env.DAILY_PBF_MD5 }}
          overwrite: true

      - name: Make release note
        run: |
          echo "## $DAILY_PBF" > note
          echo 'Daily OSM PBF file for Taiwan extraction from Geofabrik.' >> note
          echo >> note
          echo "**md5:** $(cat $DAILY_PBF_MD5 | cut -d ' ' -f1)" >> note
          echo "**source:** http://download.geofabrik.de/asia/taiwan.html" >> note
      - name: Update release note
        uses: typebrook/github-release@v2
        env:
          type: edit
          filename: note
