name: Hourly PBF update

on:
  schedule:
    - cron: '10 * * * *'
  push:
    tags: 
      - test.update*

jobs:
  update-pbf:
    runs-on: ubuntu-latest
    container:
      image: osmtw/osmctools:latest
    env:
      DAILY_PBF: taiwan-daily.osm.pbf
      LATEST_PBF: taiwan-latest.osm.pbf
      TAIWAN_BBOX: 118.1036,20.72799,122.9312,26.60305
      github_api_token: ${{ secrets.GITHUB_TOKEN }}
      repo: ${{ github.repository }}
      tag: daily-taiwan-pbf

    steps:
      - name: Check target PBF file
        uses: wei/curl@v1
        with:
          args: https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.tag }} -o release

      - name: Set target PBF file
        run: |
          grep -E '^ *"body"' release | grep "## $LATEST_PBF" && TARGET_PBF=$LATEST_PBF || TARGET_PBF=$DAILY_PBF
          echo "::set-env name=TARGET_PBF::$TARGET_PBF"

      - name: Download osm.pbf from release
        uses: wei/curl@v1
        with:
          args: -Lo target.osm.pbf https://github.com/${{ github.repository }}/releases/download/${{ env.tag }}/${{ env.TARGET_PBF }}

      - name: Update PBF file by osmctools
        run: osmupdate --hour -b=$TAIWAN_BBOX target.osm.pbf $LATEST_PBF

      - name: Upload updated PBF file as release asset
        uses: typebrook/github-release@v3
        env:
          type: asset
          filename: ${{ env.LATEST_PBF }}
          overwrite: true

      - name: Make release note
        run: |
          echo "## $DAILY_PBF" > note
          echo 'Daily OSM PBF file with extent of Taiwan, comes from Geofabrik.' >> note
          echo "Contains OSM data up to $(osmconvert $DAILY_PBF --out-timestamp)." >> note
          echo >> note
          echo '**md5:**' $(sed -En 's/^ +"body".+md5[^ ]+ ([[:alnum:]]+).+$/\1/p' release) >> note
          echo "**source:** http://download.geofabrik.de/asia/taiwan-latest.osm.pbf" >> note
          echo >> note
          echo "## $LATEST_PBF" >> note
          echo 'Updated OSM PBF file.' >> note
          echo "Contains OSM data up to $(osmconvert $LATEST_PBF --out-timestamp)." >> note
      - name: Update release note
        uses: typebrook/github-release@v3
        env:
          type: edit
          filename: note
