name: Get latest OSM PBF from Geofabrik

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  pbf:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest osm.pbf from geofabrik
        uses: wei/wget@v1
        with:
          args: http://download.geofabrik.de/asia/taiwan-latest.osm.pbf
      - name: Upload PBF file to Release Asset
        uses: typebrook/upload-release-asset@v1
        env:
          github_api_token: ${{ secrets.GITHUB_TOKEN  }}
          owner: typebrook
          repo: mapstew
          tag: daily-taiwan-pbf
          filename: taiwan-latest.osm.pbf
          overwrite: true

      - name: Download MD5 for osm.pbf
        uses: wei/wget@v1
        with:
            args: http://download.geofabrik.de/asia/taiwan-latest.osm.pbf.md5
      - name: Upload MD5 to Release Asset
        uses: typebrook/upload-release-asset@v1
        env:
          github_api_token: ${{ secrets.GITHUB_TOKEN  }}
          owner: typebrook
          repo: mapstew
          tag: daily-taiwan-pbf
          filename: taiwan-latest.osm.pbf.md5
          overwrite: true
